// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

namespace Domain.Models
{
    public partial class OrderItems
    {
        public int OrderItemsId { get; set; }
        public int? FoodId { get; set; }
        public int? OrderMasterId { get; set; }
        public int? Qty { get; set; }

        public virtual Foods Food { get; set; }
        public virtual OrderMaster OrderMaster { get; set; }
    }
}