// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models
{
    public partial class Staffs
    {
        public Staffs()
        {
            OrderMaster = new HashSet<OrderMaster>();
        }

        public string StaffId { get; set; }
        public string StaffType { get; set; }
        public DateTime? StaffLastLogin { get; set; }
        public string StaffSq { get; set; }
        public string StaffSa { get; set; }
        public string StaffPwd { get; set; }

        public virtual StaffDetails StaffDetails { get; set; }
        public virtual ICollection<OrderMaster> OrderMaster { get; set; }
    }
}