// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models
{
    public partial class StaffDetails
    {
        public string StaffId { get; set; }
        public string StaffName { get; set; }
        public string StaffGender { get; set; }
        public string StaffPhoneNumber { get; set; }
        public DateTime? StaffDob { get; set; }
        public string StaffAddress { get; set; }
        public byte[] StaffImg { get; set; }

        public virtual Staffs Staff { get; set; }
    }
}